ALTER TABLE player_houses
ADD COLUMN playername VARCHAR(255) DEFAULT NULL,
ADD COLUMN x VARCHAR(255) DEFAULT NULL,
ADD COLUMN y VARCHAR(255) DEFAULT NULL,
ADD COLUMN menu VARCHAR(255) DEFAULT 'true';
